### ISSUE TITLE
Can't build assets with Ruby 2.0.0, (activeadmin 0.6.6 ), and coffee-script 2.3.0. Windows.

### ISSUE THREAD

**Issue by primalr** [josh/ruby-coffee-script#31]
When I try to precompile my assets, it succeeds in coffee-script 2.2.0, but when trying to upgrade to 2.3.0 it fails. Right now I'm trying to build activeadmin 0.6.6 assets, but possibly it could have been anything. I'm running on windows - don't know if it is related.

Here is a complete trace:
command: bundle exec rake assets:precompile RAILS_ENV=production --trace

DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
** Invoke assets:precompile (first_time)
** Execute assets:precompile
//Ruby200/bin/ruby.exe //Ruby200/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
DL is deprecated, please use Fiddle
** Invoke assets:precompile:all (first_time)
** Invoke assets:cache:clean (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Execute assets:cache:clean
** Execute assets:precompile:all
rake aborted!
ExecJS::ProgramError: TypeError: Object doesn't support this property or method
  (in //Ruby200/lib/ruby/gems/2.0.0/gems/activeadmin-0.6.6/app/assets/javascripts/active_admin/lib/namespace.js.coffee)
//Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb:67:in `extract_result'
//Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb:32:in `exec'
//Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb:21:in `eval'
//Ruby200/lib/ruby/gems/2.0.0/gems/execjs-2.3.0/lib/execjs/external_runtime.rb:39:in `call'
//Ruby200/lib/ruby/gems/2.0.0/gems/coffee-script-2.3.0/lib/coffee_script.rb:76:in `compile'
//Ruby200/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/coffee.rb:46:in `evaluate'
//Ruby200/lib/ruby/gems/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/processed_asset.rb:16:in `initialize'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `new'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `block in build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:270:in `circular_call_protection'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:14:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/asset_with_dependencies.rb:96:in `block in resolve_dependencies'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/asset_with_dependencies.rb:90:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/asset_with_dependencies.rb:90:in `resolve_dependencies'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/sprockets/asset_with_dependencies.rb:81:in `build_required_assets'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/processed_asset.rb:20:in `initialize'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `new'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `block in build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:270:in `circular_call_protection'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:14:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/bundled_asset.rb:12:in `initialize'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `new'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:41:in `block in compile'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
//Ruby200/lib/ruby/gems/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:108:in `internal_precompile'
//Ruby200/lib/ruby/gems/2.0.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:115:in `block (3 levels) in <top (required)>'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
//Ruby200/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
//Ruby200/bin/rake:23:in `load'
//Ruby200/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile:all
rake aborted!
Command failed with status (1): [//Ruby200/bin/rub...]
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:94:in `ruby'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `ruby'
//Ruby200/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:12:in `ruby_rake_task'
//Ruby200/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
//Ruby200/lib/ruby/gems/2.0.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
//Ruby200/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
//Ruby200/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
//Ruby200/bin/rake:23:in `load'
//Ruby200/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile

**Comment by zrisher** [comment]
I'm also receiving the error `Object doesn't support this property or method` when I try to compile any coffeescript file, even an empty one, with coffee-script-source 1.9, coffee-script 2.3, coffee-rails 4.1, and rails 4.2 on Windows 64. Downgrading coffee-script-source to 1.8 fixes this.
