### ISSUE TITLE
Proposal: Move repo under rails org

### ISSUE THREAD

**Issue by josh** [josh/ruby-coffee-script#32]
I just want to make sure I'm not a bottleneck to maintaining this gem since its an important dependency of Rails. There really isn't much work to do. coffee-script changes are infrequent. But a few more people than me should have commit and gem publish access.

cc @guilleiguaran @spastorino @robin850 @rafaelfranca

**Comment by robin850** [comment]
Not sure if you meant to ping me but I can help if this repository moves to the Rails organization. :smile: :+1:

**Comment by rafaelfranca** [comment]
:shipit:
